name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Assemble Gradle
        uses: gradle/gradle-build-action@v2.1.4
        with:
          arguments: build

  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Publish gradle
        uses: gradle/gradle-build-action@v2.1.4
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        with:
          arguments: publishMavenPublicationToMavenLocal